### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by fabriciojoc** [adaptive-machine-learning/CapyMOA#137]
I followed the [installation tutorial ](https://capymoa.org/installation.html) using conda and right now, the only way it works in my system is if I run the script from the project's folder. 

Here I tried to import it in both Python and the [Getting Started tutorial](https://capymoa.org/notebooks/00_getting_started.html). In both cases I get the error `ModuleNotFoundError: No module named 'capymoa.datasets'; 'capymoa' is not a package`.

![image](https://github.com/adaptive-machine-learning/CapyMOA/assets/10869430/d4059140-ec3b-41b1-b848-b22578f7148e)

However, if I run it from the project's folder, it works.

![image](https://github.com/adaptive-machine-learning/CapyMOA/assets/10869430/a8c69ba3-8909-4d6f-bc61-35296212e1f1)

Is there any idea why this is not working? I know I can use docker, but it is always easier to use pip install and use it 😃

**Comment by hmgomes** [comment]
Hi @fabriciojoc , thanks for reporting that. @tachyonicClock can you please assist? I am a bit overwhelmed today

**Comment by tachyonicClock** [comment]
Hi @fabriciojoc thanks for your issue. Did you install using `pip install capymoa` or 
```
git clone git@github.com:adaptive-machine-learning/CapyMOA.git # or your fork
cd CapyMOA
pip install --editable ".[dev]"
```
?

**Comment by tachyonicClock** [comment]
On second glance of your bug report it looks like a name conflict between you script and the capymoa module. Python is trying to look for `capymoa.*` in `capymoa.py`. This explains why you can import capymoa in other directories where the conflict does not exist.

Try renaming your script `capymoa.py` to `run_capymoa.py`.

**Comment by fabriciojoc** [comment]
> Hi @fabriciojoc thanks for your issue. Did you install using `pip install capymoa` or
> 
> ```
> git clone git@github.com:adaptive-machine-learning/CapyMOA.git # or your fork
> cd CapyMOA
> pip install --editable ".[dev]"
> ```
> 
> ?

Hi @tachyonicClock. Thanks for checking! I tried using `pip install capymoa` and it didn't work. Then I used `pip install --editable ".[dev]"` and it started working only in the project's folder.

**Comment by fabriciojoc** [comment]
> On second glance of your bug report it looks like a name conflict between your script and the capymoa module. Python is trying to look for `capymoa.*` in `capymoa.py`. This explains why you can import capymoa in other directories where the conflict does not exist.
> 
> Try renaming your script `capymoa.py` to `run_capymoa.py`.
> 
> (See https://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap for more)

@tachyonicClock you were right! I think my Python was trying to import capybara through the script I created, even when I just typed `import capybara` in the Python terminal. So in the end, it is not a bug! Just to clarify, now it is working even without conda. By just using `pip install capymoa`, I can already use it! Thanks for clarifying!

**Comment by tachyonicClock** [comment]
Glad we could help :D
