### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by tachyonicClock** [adaptive-machine-learning/CapyMOA#145]
Error encountered after installing capymoa. **Originally reported by @alexs4ndro on the discord.** 
```
C:\Users\alexs>python -c "import capymoa; print(capymoa.version)"
A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000000000000, pid=1880, tid=21064
JRE version:  (17.0.9+9) (build )
Java VM: OpenJDK 64-Bit Server VM (17.0.9+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
Problematic frame:
C  [jimage.dll+0x1827]
No core dump will be written. Minidumps are not enabled by default on client versions of Windows
An error report file with more information is saved as:
C:\Users\alexs\hs_err_pid1880.log
C:\Users\alexs>
```
In my opinion this looks like an issue caused by using capymoa with a particular version of Java on windows. 
I found  this person online https://github.com/microsoft/openjdk/issues/607 having a similar issue with another application.

**Comment by hmgomes** [comment]
Hi @tachyonicClock , any progress on this one? In case we don't have any action to take, we could consider closing this

**Comment by tachyonicClock** [comment]
If I recall I think this was fixed by using a newer version. We can probably close it.
