### ISSUE TITLE
Headaches for Users

### ISSUE THREAD

**Issue by tachyonicClock** [adaptive-machine-learning/CapyMOA#26]
Some parts of Capymoa risk becoming headaches for new users. This issue exists to help discover and mitigate these risks. What parts of Capymoa do you find counterintuitive?

- A new user could be confused about if they should be using `capymoa.stream.instance.Instance`, `capymoa.stream.instance._JavaInstance`, `com.yahoo.labs.samoa.instance.DenseInstance`, `moa.core.InstanceExample`,  `capymoa.stream.instance.NpInstance`
- The schema can be cumbersome. Instance and classifiers need it to function currently.
- `y_index` vs `y_label`

**Comment by hmgomes** [comment]
Going to close this issue as most of these _headaches_ were either solved already or mapped to tasks in our backlog
