### ISSUE TITLE
`CSVStream` is slow.

### ISSUE THREAD

**Issue by tachyonicClock** [adaptive-machine-learning/CapyMOA#42]
Hey @nuwangunasekara I looked into why the CSV reader was slow while trying to fix the tests. I did some basic benchmarks and found the ARFF stream streams `59,227` instances a second, and the CSV stream loads `3,177` a second. This is a very significant performance decrease.  I decided to profile it to see what the potential issue was.

- I believe most of the slowness comes from opening a file for each instance. It should be possible to keep one file open and use it for each instance.

In pseudo code:
```
with open("csv.csv") as f:
        data = np.genfromtxt(f, max_rows=1)
        ...
        data = np.genfromtxt(f, max_rows=1)
        ...
        data = np.genfromtxt(f, max_rows=1)
```
Rather than
```
data = np.genfromtxt("csv.csv", skip=1, max_rows=1)
data = np.genfromtxt("csv.csv", skip=2, max_rows=1)
data = np.genfromtxt("csv.csv", skip=3, max_rows=1)
data = np.genfromtxt("csv.csv", skip=4, max_rows=1)
```
**This will also avoid skipping through each row in the CSV for each call to the next instance.**

- I'm not convinced `genfromtxt` is the fastest function when loading one instance at a time. I found the standard library CSV reader to be faster. Of course, I'm not sure how CSVReader should handle non-float datatypes.
```python
  with open("data/electricity_tiny.csv") as f:
      csv_file = csv.reader(f)
      next(f)

      start = time.time()
      n = 0

      for row in csv_file:
          x = np.array(row, dtype=float)
          n += 1

      frequency = n / (time.time() - start)

      print(f"csv reader frequency: {frequency}")

  with open("data/electricity_tiny.csv") as f:
      next(f)

      start = time.time()
      n = 0

      while True:
          n += 1
          x = np.genfromtxt(f, delimiter=",", dtype=float, max_rows=1)
          if x.size == 0:
              break
          
      frequency = n / (time.time() - start)

      print(f"genfromtxt frequency: {frequency}")
  ```
csv reader frequency: 672757.0775523297
genfromtxt frequency: 22945.635917751366

### Profiling
To profile the relevant piece of the code:
```python
from cProfile import Profile

start = time.time()
stream = stream_from_file("data/electricity_tiny.csv")
load_time = time.time() - start

start = time.time()
with Profile() as profile:
    n = 0
    while stream.has_more_instances():
        stream.next_instance()
        n += 1

    profile.dump_stats("csv.prof")

frequency = n / (time.time()  - start) 

print(f"Load time: {load_time}")
print(f"Frequency: {frequency}")

```
I used https://jiffyclub.github.io/snakeviz/ to visualize the profile files. I have also attached the profiles for convenience.
[csv_original.prof.tar.gz](https://github.com/hmgomes/CapyMOA/files/14972573/csv_original.prof.tar.gz)

![image](https://github.com/hmgomes/CapyMOA/assets/37557393/2d0ffaab-5173-46b5-a760-6bfe35976060)

**Comment by hmgomes** [comment]
CSVStream might be implemented from the MOA side, we have an updated version on capymoa side but there is still room for improvement
